# -*- coding: utf-8 -*-

#  implementation generated from reading ui file 'test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TestUi(object):
    def setupUi(self):
        self.pushButton = QtWidgets.QPushButton()
        self.pushButton.setGeometry(QtCore.QRect(530, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton()
        self.pushButton_2.setGeometry(QtCore.QRect(530, 200, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox()
        self.comboBox.setGeometry(QtCore.QRect(160, 390, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_3 = QtWidgets.QPushButton()
        self.pushButton_3.setGeometry(QtCore.QRect(260, 390, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel()
        self.label.setGeometry(QtCore.QRect(476, 20, 101, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel()
        self.label_2.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit()
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 60, 421, 291))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_4 = QtWidgets.QPushButton()
        self.pushButton_4.setGeometry(QtCore.QRect(530, 330, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox_2 = QtWidgets.QComboBox()
        self.comboBox_2.setGeometry(QtCore.QRect(50, 390, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_3 = QtWidgets.QLabel()
        self.label_3.setGeometry(QtCore.QRect(180, 20, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel()
        self.label_4.setGeometry(QtCore.QRect(110, 20, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel()
        self.label_5.setGeometry(QtCore.QRect(250, 20, 47, 13))
        self.label_5.setObjectName("label_5")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName()

    def retranslateUi(self, ):
        self.pushButton.setText("Pass")
        self.pushButton_2.setText("Fail")
        self.pushButton_3.setText("Start")
        self.label.setText("URL")
        self.label_2.setText("Last Seen Date")
        self.pushButton_4.setText("Flip")
        self.label_3.setText("Pass Rate")
        self.label_4.setText("TextLabel")
        self.label_5.setText("TextLabel")
